### ISSUE TITLE
Bot not verified

### ISSUE THREAD

**Issue by thehappylighthouse** [rtomrud/apolloniabot#3]
Intent permission problem, please fix it so it can go in more than 100 servers.

**Comment by rtomrud** [comment]
The bot doesn't ask for any Privileged Intents, but it has to go through Discord's verification process anyway before it can be added to more than 100 servers, according to the new [Discord bot verification policy](https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting).

**Comment by thehappylighthouse** [comment]
> 

So will you put it for verification, I'll be glad if u do its an amazing bot

**Comment by rtomrud** [comment]
Yes, I'm submitting it for verification. You will be able to add it to your server once it's approved.

**Comment by thehappylighthouse** [comment]
Thank you :+1:

**Comment by thehappylighthouse** [comment]
Been like two weeks, has Discord denied the bot?

**Comment by thehappylighthouse** [comment]
Any update?

**Comment by thehappylighthouse** [comment]
I see you worked on the bot meanwhile, looks like the bot wasn't cutting for some Discord requirement.

**Comment by rtomrud** [comment]
I haven't had much time lately to submit all the information requested by Discord during the verification process. Sorry about that. It should be done soon!

Meanwhile I was preparing the infrastructure so that the bot can scale smoothly after it does get verified and joins more servers.

**Comment by thehappylighthouse** [comment]
> 

Hey, any update on the process?

**Comment by rtomrud** [comment]
I apologize for the wait, but Discord has made their bot verification
process more strict so there's a bit of bureocracy to go through.

I have to make a GDPR-compliant Privacy Policy, the Terms of Service and a
website. That should be done by next week. Then Discord will have to finish
verifying the submitted info, which I hope won't take long.

**Comment by ramiz03** [comment]
any update on this?

**Comment by rtomrud** [comment]
Bots that play music can no longer be verified according to Discord's policy, so it can't be a public bot.
